# MA3K7 Assignment 1 

**Student Number: 2110308**

In [1]:
import numpy as np
import random

The code below runs 16 random simulations of the game on a 2x2 grid and prints out games which create a singular matrix. The aim is to draw patterns in order to implement a strategy for 2x2 games where I go first. 

In [8]:
#Calculate the determinant of a 2x2 matrix.
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Simulate a game on an n x n grid with random placement of 0s and 1s.
def simulate_game(n):
    # Initialize an n x n grid with -1 (to represent empty cells)
    grid = np.full((n, n), -1)
    
    # Players take turns to fill the grid
    for turn in range(n*n):
        # Choose a random empty cell
        empty_cells = np.argwhere(grid == -1)
        choice = random.choice(empty_cells)
        
        # Fill the cell with 0 or 1 depending on the turn
        #Player who inputs 0s goes first
        grid[tuple(choice)] = turn % 2
    
    return grid

# Simulate a series of games for a 2x2 matrix and calculate the determinant for each final matrix
n = 2
num_games = 16  # Number of games to simulate
zero_determinant_games = 0 #Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")
print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")


Game #2 with zero determinant:
[[1 0]
 [1 0]]

Game #4 with zero determinant:
[[0 0]
 [1 1]]

Game #5 with zero determinant:
[[1 0]
 [1 0]]

Game #9 with zero determinant:
[[0 0]
 [1 1]]

Game #10 with zero determinant:
[[1 0]
 [1 0]]

Game #13 with zero determinant:
[[1 1]
 [0 0]]

Game #14 with zero determinant:
[[1 1]
 [0 0]]

Game #15 with zero determinant:
[[0 1]
 [0 1]]

Total games with zero determinant: 8 out of 16


The code below runs 20 random simulations of the game on a 3 x 3 grid and prints out games that result in a singular matrix. The aim, as with the code above, is to draw patterns that can be incorporated into a strategy for 3 x 3 grids.

In [9]:
#Calculate the determinant of a 3x3 matrix.
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Simulate a game on an n x n grid with random placement of 0s and 1s.
def simulate_game(n):
    # Initialize an n x n grid with -1 (to represent empty cells)
    grid = np.full((n, n), -1)
    
    # Players take turns to fill the grid
    for turn in range(n*n):
        # Choose a random empty cell
        empty_cells = np.argwhere(grid == -1)
        choice = random.choice(empty_cells)
        
        # Fill the cell with 0 or 1 depending on the turn
        #Player who inputs 0s goes first
        grid[tuple(choice)] = turn % 2
    
    return grid

# Simulate a series of games for a 2x2 matrix and calculate the determinant for each final matrix
n = 3
num_games = 20  # Number of games to simulate
zero_determinant_games = 0 #Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")
print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")

Game #1 with zero determinant:
[[0 1 0]
 [0 1 0]
 [1 1 0]]

Game #2 with zero determinant:
[[0 1 1]
 [1 0 1]
 [0 0 0]]

Game #3 with zero determinant:
[[0 0 1]
 [1 0 0]
 [1 0 1]]

Game #4 with zero determinant:
[[1 0 0]
 [1 1 0]
 [0 1 0]]

Game #5 with zero determinant:
[[1 1 0]
 [1 1 0]
 [0 0 0]]

Game #7 with zero determinant:
[[0 1 1]
 [0 0 1]
 [0 1 0]]

Game #8 with zero determinant:
[[0 0 1]
 [0 1 1]
 [0 0 1]]

Game #9 with zero determinant:
[[0 1 1]
 [0 1 0]
 [0 0 1]]

Game #10 with zero determinant:
[[0 0 1]
 [1 0 1]
 [1 0 0]]

Game #11 with zero determinant:
[[1 0 1]
 [1 0 0]
 [1 0 0]]

Game #12 with zero determinant:
[[1 0 1]
 [0 0 1]
 [0 0 1]]

Game #13 with zero determinant:
[[0 0 0]
 [1 0 1]
 [1 1 0]]

Game #14 with zero determinant:
[[1 0 1]
 [0 0 0]
 [1 1 0]]

Game #15 with zero determinant:
[[0 0 0]
 [1 1 0]
 [0 1 1]]

Game #18 with zero determinant:
[[1 1 0]
 [1 0 0]
 [1 0 0]]

Game #19 with zero determinant:
[[1 1 1]
 [0 0 0]
 [1 0 0]]

Total games with zero determinan

The code below prints undesired completed game states for 3 x 3 grids in order to verify a conjecture.

In [10]:
undesired_games = 0
for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det != 0:
        undesired_games += 1
        print(f"Game #{game + 1} with non-zero determinant:\n{game_result}\n")
print(f"Total games with non-zero determinant: {undesired_games} out of {num_games}")

Game #2 with non-zero determinant:
[[0 1 1]
 [1 0 0]
 [0 0 1]]

Game #3 with non-zero determinant:
[[1 1 0]
 [0 1 0]
 [0 0 1]]

Game #5 with non-zero determinant:
[[1 0 0]
 [0 0 1]
 [0 1 1]]

Game #9 with non-zero determinant:
[[1 0 0]
 [0 0 1]
 [1 1 0]]

Game #11 with non-zero determinant:
[[0 0 1]
 [0 1 0]
 [1 0 1]]

Game #16 with non-zero determinant:
[[0 1 0]
 [1 0 0]
 [1 0 1]]

Game #18 with non-zero determinant:
[[0 0 1]
 [0 1 0]
 [1 0 1]]

Total games with non-zero determinant: 7 out of 20


The code below runs a simulation of games on a 3 x 3 grid with the strategy of ensuring there is a zero in each row by the end of the game. This code is also under the assumption that I go first.

In [31]:
#Calculate the determinant of a 3x3 matrix
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Simulate a game on an n x n grid with strategic placement of 0s by me
def simulate_game(n):
    # Initialize an n x n grid with -1 (to represent empty cells)
    grid = np.full((n, n), -1)
    
    # Track rows that already have a '0' to ensure diversity in placement
    rows_with_zero = set()
    
    # Players take turns to fill the grid
    for turn in range(n*n):
        if turn % 2 == 0:  #I go first
             # Identify rows without a '0'
            available_rows = [r for r in range(n) if r not in rows_with_zero]
            if len(rows_with_zero) < n:
                if available_rows:
                    row_choice = random.choice(available_rows)
                    # Find empty cells in the chosen row
                    empty_cells_in_row = np.argwhere(grid[row_choice, :] == -1)
                    if len(empty_cells_in_row) > 0:
                        col_choice = random.choice(empty_cells_in_row)[0]  # Select column
                        grid[row_choice, col_choice] = 0
                        rows_with_zero.add(row_choice)  # Update the set of rows with a '0'
            else:
                # Once every row has a '0', place '0's randomly
                empty_cells = np.argwhere(grid == -1)
                if empty_cells.size > 0:
                    choice = random.choice(empty_cells)
                    grid[choice[0], choice[1]] = 0
                
        else:
            #My friend places their number in any random empty cell
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:  # Check if there are still empty cells
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
    
    return grid

n = 3 #Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0  # Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")


Game #1 with zero determinant:
[[0 0 0]
 [1 1 0]
 [1 0 1]]

Game #2 with zero determinant:
[[0 1 0]
 [1 0 1]
 [0 1 0]]

Game #4 with zero determinant:
[[0 1 1]
 [0 1 0]
 [0 1 0]]

Game #5 with zero determinant:
[[1 1 0]
 [1 0 1]
 [0 0 0]]

Game #6 with zero determinant:
[[1 1 0]
 [1 0 1]
 [0 0 0]]

Game #7 with zero determinant:
[[1 1 0]
 [1 0 1]
 [0 0 0]]

Game #8 with zero determinant:
[[0 0 1]
 [0 0 1]
 [0 1 1]]

Game #9 with zero determinant:
[[1 1 0]
 [0 1 0]
 [1 0 0]]

Game #10 with zero determinant:
[[0 0 1]
 [0 0 1]
 [1 0 1]]

Game #11 with zero determinant:
[[0 1 1]
 [0 0 0]
 [0 1 1]]

Game #12 with zero determinant:
[[1 0 1]
 [1 0 0]
 [0 0 1]]

Game #13 with zero determinant:
[[0 0 0]
 [0 1 1]
 [1 1 0]]

Game #14 with zero determinant:
[[1 0 1]
 [0 1 1]
 [0 0 0]]

Game #16 with zero determinant:
[[1 1 0]
 [1 0 0]
 [0 1 0]]

Game #17 with zero determinant:
[[1 0 0]
 [0 1 1]
 [1 0 0]]

Game #19 with zero determinant:
[[0 0 1]
 [0 0 1]
 [1 1 0]]

Game #21 with zero determinant:


The code below comprises of me attempting to create a zero column and otherwise attempting to ensure the determinant of the 2x2 submatrix(es) formed by laplace expansion is 0. 

In [45]:
#Calculate the determinant of a matrix
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Find cells that are not in the disrupted rows and columns
def find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns):
    non_disrupted_cells = []
    for row in range(grid.shape[0]):
        for col in range(grid.shape[1]):
            if row not in disrupted_rows and col not in disrupted_columns and grid[row, col] == -1:
                non_disrupted_cells.append((row, col))
    return non_disrupted_cells

#Simulate a game with a dynamic strategy after disruption
def simulate_game(n):
    grid = np.full((n, n), -1)  # Initialize grid
    
    disrupted_rows = set()
    disrupted_columns = set()

    for turn in range(n*n):
        if turn % 2 == 0:  # Friend's turn
            # Friend tries to disrupt by placing "1"s
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
                # Update disrupted rows and columns
                disrupted_rows.add(choice[0])
                disrupted_columns.add(choice[1])
        else:  # My turn
            # Identify non-disrupted cells for strategic placement
            non_disrupted_cells = find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns)
            if non_disrupted_cells:
                # Place "0" strategically in non-disrupted part of the grid
                choice = random.choice(non_disrupted_cells)
                grid[choice[0], choice[1]] = 0
            else:
                # If no non-disrupted cells are left, place "0" in any available cell
                empty_cells = np.argwhere(grid == -1)
                if empty_cells.size > 0:
                    choice = random.choice(empty_cells)
                    grid[choice[0], choice[1]] = 0

    return grid

n = 3  # Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0  # Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")


Game #1 with zero determinant:
[[0 1 0]
 [1 0 1]
 [1 0 1]]

Game #3 with zero determinant:
[[0 0 0]
 [1 1 0]
 [1 1 1]]

Game #4 with zero determinant:
[[1 0 1]
 [0 0 0]
 [1 1 1]]

Game #8 with zero determinant:
[[0 1 0]
 [1 1 0]
 [1 1 0]]

Game #9 with zero determinant:
[[0 0 0]
 [1 0 1]
 [1 1 1]]

Game #10 with zero determinant:
[[0 1 1]
 [0 1 1]
 [0 1 0]]

Game #13 with zero determinant:
[[1 1 0]
 [1 1 0]
 [0 1 0]]

Game #14 with zero determinant:
[[0 0 1]
 [0 0 1]
 [1 1 1]]

Game #16 with zero determinant:
[[1 1 0]
 [1 0 0]
 [1 1 0]]

Game #17 with zero determinant:
[[1 0 0]
 [1 0 1]
 [1 0 1]]

Game #18 with zero determinant:
[[0 0 1]
 [0 0 1]
 [1 1 1]]

Game #21 with zero determinant:
[[1 1 0]
 [0 0 0]
 [1 1 1]]

Game #22 with zero determinant:
[[0 1 0]
 [0 1 1]
 [0 1 1]]

Game #25 with zero determinant:
[[0 0 0]
 [1 1 1]
 [1 0 1]]

Game #26 with zero determinant:
[[0 1 1]
 [0 1 0]
 [0 1 1]]

Game #27 with zero determinant:
[[0 0 1]
 [1 1 1]
 [0 0 1]]

Game #28 with zero determinan

The code below observes games which produce non-singular matrices.

In [46]:
undesired_games = 0
for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det != 0:
        undesired_games += 1
        print(f"Game #{game + 1} with non-zero determinant:\n{game_result}\n")
print(f"Total games with non-zero determinant: {undesired_games} out of {num_games}")

Game #2 with non-zero determinant:
[[0 1 0]
 [1 1 0]
 [0 1 1]]

Game #3 with non-zero determinant:
[[0 0 1]
 [1 0 0]
 [1 1 1]]

Game #5 with non-zero determinant:
[[1 0 1]
 [0 1 1]
 [0 0 1]]

Game #7 with non-zero determinant:
[[0 1 1]
 [1 1 0]
 [0 1 0]]

Game #11 with non-zero determinant:
[[1 1 0]
 [1 0 1]
 [1 0 0]]

Game #12 with non-zero determinant:
[[0 0 1]
 [1 1 1]
 [0 1 0]]

Game #13 with non-zero determinant:
[[1 0 1]
 [1 0 0]
 [0 1 1]]

Game #14 with non-zero determinant:
[[0 1 1]
 [1 1 0]
 [1 0 0]]

Game #19 with non-zero determinant:
[[0 1 1]
 [1 1 0]
 [0 1 0]]

Game #22 with non-zero determinant:
[[1 0 1]
 [0 1 0]
 [1 1 0]]

Game #23 with non-zero determinant:
[[1 0 0]
 [1 0 1]
 [1 1 0]]

Game #24 with non-zero determinant:
[[1 0 1]
 [0 0 1]
 [1 1 0]]

Game #25 with non-zero determinant:
[[1 1 1]
 [0 0 1]
 [1 0 0]]

Game #26 with non-zero determinant:
[[0 1 1]
 [1 0 1]
 [0 0 1]]

Game #27 with non-zero determinant:
[[1 1 0]
 [1 0 1]
 [1 0 0]]

Game #34 with non-zero determ

In [50]:
#Calculate the determinant of a matrix
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Finds a move that blocks my friend from creating a column of '1's
def find_blocking_move(grid, n):
    for col in range(n):
        if np.sum(grid[:, col] == 1) == n - 1 and np.any(grid[:, col] == -1):
            # Column is one move away from being a column of '1's, find the empty cell to block
            row = np.where(grid[:, col] == -1)[0][0]
            return (row, col)
    return None

#Find cells that are not in the disrupted rows and columns
def find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns):
    non_disrupted_cells = []
    for row in range(grid.shape[0]):
        for col in range(grid.shape[1]):
            if row not in disrupted_rows and col not in disrupted_columns and grid[row, col] == -1:
                non_disrupted_cells.append((row, col))
    return non_disrupted_cells

#Simulate a game with a dynamic strategy after disruption
def simulate_game(n):
    grid = np.full((n, n), -1)  # Initialize grid
    
    disrupted_rows = set()
    disrupted_columns = set()

    for turn in range(n*n):
        if turn % 2 == 0:  # Friend's turn
            # Friend tries to disrupt by placing "1"s
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
                # Update disrupted rows and columns
                disrupted_rows.add(choice[0])
                disrupted_columns.add(choice[1])
        else:  # My turn
            # First, check if we need to block a column of '1's
            blocking_move = find_blocking_move(grid, n)
            if blocking_move:
                grid[blocking_move] = 0
            else:
                # If no need to block, proceed with other strategies
                # This includes creating zero columns or placing "0"s strategically elsewhere
                # Identify non-disrupted cells for strategic placement
                non_disrupted_cells = find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns)
                if non_disrupted_cells:
                    # Place "0" strategically in non-disrupted part of the grid
                    choice = random.choice(non_disrupted_cells)
                    grid[choice[0], choice[1]] = 0
                else:
                    # If no non-disrupted cells are left, place "0" in any available cell
                    empty_cells = np.argwhere(grid == -1)
                    if empty_cells.size > 0:
                        choice = random.choice(empty_cells)
                        grid[choice[0], choice[1]] = 0

    return grid

n = 3  # Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0  # Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")

Game #1 with zero determinant:
[[1 1 1]
 [0 0 0]
 [0 1 1]]

Game #2 with zero determinant:
[[0 0 0]
 [1 0 1]
 [1 1 1]]

Game #3 with zero determinant:
[[0 1 1]
 [0 0 0]
 [1 1 1]]

Game #7 with zero determinant:
[[1 1 1]
 [0 0 0]
 [1 0 1]]

Game #10 with zero determinant:
[[0 0 0]
 [0 1 1]
 [1 1 1]]

Game #11 with zero determinant:
[[1 1 1]
 [1 0 1]
 [0 0 0]]

Game #12 with zero determinant:
[[1 1 1]
 [1 1 0]
 [0 0 0]]

Game #15 with zero determinant:
[[1 0 1]
 [0 0 0]
 [1 1 1]]

Game #16 with zero determinant:
[[1 1 1]
 [1 0 1]
 [0 0 0]]

Game #17 with zero determinant:
[[1 1 1]
 [0 0 0]
 [0 1 1]]

Game #18 with zero determinant:
[[1 1 0]
 [0 0 0]
 [1 1 1]]

Game #21 with zero determinant:
[[0 0 0]
 [1 1 0]
 [1 1 1]]

Game #26 with zero determinant:
[[0 1 1]
 [1 1 1]
 [0 0 0]]

Game #27 with zero determinant:
[[0 0 0]
 [1 1 0]
 [1 1 1]]

Game #29 with zero determinant:
[[1 1 1]
 [0 0 0]
 [1 1 0]]

Game #32 with zero determinant:
[[1 1 1]
 [0 0 0]
 [1 0 1]]

Game #35 with zero determina

In [51]:
undesired_games = 0
for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det != 0:
        undesired_games += 1
        print(f"Game #{game + 1} with non-zero determinant:\n{game_result}\n")
print(f"Total games with non-zero determinant: {undesired_games} out of {num_games}")

Game #1 with non-zero determinant:
[[1 0 0]
 [0 1 1]
 [1 0 1]]

Game #4 with non-zero determinant:
[[1 0 0]
 [0 0 1]
 [1 1 1]]

Game #5 with non-zero determinant:
[[1 1 1]
 [0 1 0]
 [1 0 0]]

Game #10 with non-zero determinant:
[[0 1 1]
 [1 0 1]
 [0 1 0]]

Game #12 with non-zero determinant:
[[1 0 0]
 [0 1 0]
 [1 1 1]]

Game #13 with non-zero determinant:
[[1 0 0]
 [0 0 1]
 [1 1 1]]

Game #15 with non-zero determinant:
[[0 1 1]
 [1 0 0]
 [1 0 1]]

Game #16 with non-zero determinant:
[[1 1 0]
 [1 0 1]
 [0 1 0]]

Game #19 with non-zero determinant:
[[1 0 0]
 [1 0 1]
 [0 1 1]]

Game #20 with non-zero determinant:
[[1 0 0]
 [1 1 1]
 [0 1 0]]

Game #21 with non-zero determinant:
[[0 1 1]
 [1 0 1]
 [0 1 0]]

Game #24 with non-zero determinant:
[[0 1 0]
 [0 1 1]
 [1 0 1]]

Game #25 with non-zero determinant:
[[0 1 1]
 [1 0 1]
 [0 1 0]]

Game #26 with non-zero determinant:
[[0 1 0]
 [0 1 1]
 [1 0 1]]

Game #27 with non-zero determinant:
[[1 0 1]
 [0 1 1]
 [1 0 0]]

Game #28 with non-zero deter

This code is a replica of the main one above but I modify my strategy to increase the probability that the 2x2 submatrix created is singular:

In [53]:
#Calculate the determinant of a matrix
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Finds a move that blocks my friend from creating a column of '1's
def find_blocking_move(grid, n):
    for col in range(n):
        if np.sum(grid[:, col] == 1) == n - 1 and np.any(grid[:, col] == -1):
            # Column is one move away from being a column of '1's, find the empty cell to block
            row = np.where(grid[:, col] == -1)[0][0]
            return (row, col)
    return None

#Find cells that are not in the disrupted rows and columns
def find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns):
    non_disrupted_cells = []
    for row in range(grid.shape[0]):
        for col in range(grid.shape[1]):
            if row not in disrupted_rows and col not in disrupted_columns and grid[row, col] == -1:
                non_disrupted_cells.append((row, col))
    return non_disrupted_cells

#Simulate a game with a dynamic strategy after disruption
def simulate_game(n):
    grid = np.full((n, n), -1)  # Initialize grid
    
    disrupted_rows = set()
    disrupted_columns = set()

    for turn in range(n*n):
        if turn % 2 == 0:  # Friend's turn
            # Friend tries to disrupt by placing "1"s
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
                # Update disrupted rows and columns
                disrupted_rows.add(choice[0])
                disrupted_columns.add(choice[1])
        else:  # My turn
            # First, check if we need to block a column of '1's
            blocking_move = find_blocking_move(grid, n)
            if blocking_move:
                grid[blocking_move] = 0
            else:
                # If no need to block, proceed with other strategies
                # This includes creating zero columns or placing "0"s strategically elsewhere
                # Identify non-disrupted cells for strategic placement to 
                non_disrupted_cells = find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns)
                if non_disrupted_cells:
                    # Target columns not disrupted for placing "0" to attempt creating a zero column
                    target_cols = [col for col in range(n) if col not in disrupted_columns]
                    placed = False
                    for col in target_cols:
                        if np.any(grid[:, col] == -1):  # Check if the column has empty cells
                            empty_cells_in_col = np.argwhere(grid[:, col] == -1)
                            row_choice = random.choice(empty_cells_in_col)[0]
                            grid[row_choice, col] = 0
                            placed = True
                            break
                else:
                    # If no non-disrupted cells are left, place "0" in any available cell
                    empty_cells = np.argwhere(grid == -1)
                    if empty_cells.size > 0:
                        choice = random.choice(empty_cells)
                        grid[choice[0], choice[1]] = 0

    return grid

n = 3  # Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0  # Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")

Game #3 with zero determinant:
[[1 1 1]
 [0 0 0]
 [1 1 0]]

Game #4 with zero determinant:
[[1 0 1]
 [1 1 1]
 [0 0 0]]

Game #7 with zero determinant:
[[0 1 1]
 [1 1 1]
 [0 0 0]]

Game #8 with zero determinant:
[[0 0 1]
 [1 1 0]
 [1 1 0]]

Game #10 with zero determinant:
[[1 1 1]
 [1 0 1]
 [0 0 0]]

Game #17 with zero determinant:
[[0 0 1]
 [1 1 0]
 [1 1 0]]

Game #22 with zero determinant:
[[1 0 1]
 [1 0 1]
 [0 1 0]]

Game #24 with zero determinant:
[[1 1 0]
 [1 1 0]
 [0 0 1]]

Game #26 with zero determinant:
[[0 0 0]
 [1 1 0]
 [1 1 1]]

Game #28 with zero determinant:
[[1 1 0]
 [0 0 1]
 [1 1 0]]

Game #29 with zero determinant:
[[1 1 0]
 [0 0 0]
 [1 1 1]]

Game #35 with zero determinant:
[[1 1 0]
 [1 1 0]
 [0 0 1]]

Game #38 with zero determinant:
[[0 0 0]
 [1 1 1]
 [0 1 1]]

Game #40 with zero determinant:
[[1 0 1]
 [0 1 0]
 [1 0 1]]

Game #42 with zero determinant:
[[0 1 1]
 [0 0 0]
 [1 1 1]]

Game #43 with zero determinant:
[[0 1 1]
 [1 0 0]
 [0 1 1]]

Game #47 with zero determina

The two cells below, together, test my strategy which exploits the rule of sarrus for 3x3 matrices

The code below prints out all entries that satisfy the stricter requirement that the zeros must be in each colour of both grids at least once.

In [54]:
from itertools import product

# Define color groups for both schemes
color_groups_scheme1 = {
    'purple': [(0, 0), (1, 1), (2, 2)],
    'blue': [(0, 1), (1, 2), (2, 0)],
    'orange': [(0, 2), (1, 0), (2, 1)],
}
color_groups_scheme2 = {
    'yellow': [(0, 0), (1, 2), (2, 1)],
    'red': [(1, 1), (2, 0), (0, 2)],
    'green': [(2, 2), (0, 1), (1, 0)],
}

# Generate all combinations of 3 coordinates by choosing one from each color in the first scheme
combinations_scheme1 = list(product(color_groups_scheme1['purple'], color_groups_scheme1['blue'], color_groups_scheme1['orange']))
# Generate all combinations of 3 coordinates by choosing one from each color in the second scheme
combinations_scheme2 = list(product(color_groups_scheme2['yellow'], color_groups_scheme2['red'], color_groups_scheme2['green']))

# Normalize combinations by sorting the tuples to make comparison possible regardless of order
normalized_combinations_scheme1 = {tuple(sorted(combo)) for combo in combinations_scheme1}
normalized_combinations_scheme2 = {tuple(sorted(combo)) for combo in combinations_scheme2}

# Find intersections of the two sets
intersection_combinations = normalized_combinations_scheme1.intersection(normalized_combinations_scheme2)

# Print out arrays that are present in both lists
for combo in intersection_combinations:
    print(combo)


((0, 0), (0, 1), (0, 2))
((2, 0), (2, 1), (2, 2))
((0, 1), (1, 1), (2, 1))
((1, 0), (1, 1), (1, 2))
((0, 0), (1, 0), (2, 0))
((0, 2), (1, 2), (2, 2))


In [55]:
#Calculate the determinant of a 3x3 matrix
def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Simulate a game on an n x n grid with strategic placement of 0s by me
def simulate_game(n):
    # Initialize an n x n grid with -1 (to represent empty cells)
    grid = np.full((n, n), -1)
    
    # Define color groups for both color schemes
    color_groups_scheme1 = {
        'purple': [(0, 0), (1, 1), (2, 2)],
        'blue': [(0, 1), (1, 2), (2, 0)],
        'orange': [(0, 2), (1, 0), (2, 1)],
    }
    color_groups_scheme2 = {
        'yellow': [(0, 0), (1, 2), (2, 1)],
        'red': [(1, 1), (2, 0), (0, 2)],
        'green': [(2, 2), (0, 1), (1, 0)],
    }
    
    # Combine color groups from both schemes for comprehensive strategy
    all_color_groups = {**color_groups_scheme1, **color_groups_scheme2}
    
    # Players take turns to fill the grid
    for turn in range(n*n):
        if turn % 2 == 0:  # I go first
            # Check each color group for the presence of '0'
            for color, cells in all_color_groups.items():
                if not any(grid[r, c] == 0 for r, c in cells):
                    # Find empty cells in the color group
                    empty_cells_in_group = [cell for cell in cells if grid[cell] == -1]
                    if empty_cells_in_group:
                        row_choice, col_choice = random.choice(empty_cells_in_group)
                        grid[row_choice, col_choice] = 0
                        break
            else:
                # Once every color group has a '0', place '0's randomly
                empty_cells = np.argwhere(grid == -1)
                if empty_cells.size > 0:
                    choice = random.choice(empty_cells)
                    grid[choice[0], choice[1]] = 0
        else:
            # My friend places their number in any random empty cell
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
    
    return grid

n = 3  # Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0  # Initiate the number of games that result in a zero-determinant matrix

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
        print(f"Game #{game + 1} with zero determinant:\n{game_result}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")


Game #1 with zero determinant:
[[1 0 0]
 [1 0 0]
 [1 1 0]]

Game #2 with zero determinant:
[[1 1 0]
 [0 0 0]
 [1 1 0]]

Game #3 with zero determinant:
[[1 0 0]
 [1 0 1]
 [1 0 0]]

Game #4 with zero determinant:
[[0 1 1]
 [0 0 0]
 [1 0 1]]

Game #5 with zero determinant:
[[1 1 0]
 [0 1 0]
 [0 1 0]]

Game #6 with zero determinant:
[[1 0 0]
 [0 1 0]
 [1 1 0]]

Game #7 with zero determinant:
[[1 1 1]
 [1 0 0]
 [0 0 0]]

Game #8 with zero determinant:
[[0 1 1]
 [0 0 0]
 [1 0 1]]

Game #9 with zero determinant:
[[0 1 0]
 [0 1 0]
 [1 1 0]]

Game #10 with zero determinant:
[[0 0 0]
 [1 0 1]
 [1 1 0]]

Game #11 with zero determinant:
[[1 0 0]
 [1 0 0]
 [0 1 1]]

Game #12 with zero determinant:
[[1 1 0]
 [0 0 0]
 [0 1 1]]

Game #15 with zero determinant:
[[0 1 1]
 [0 0 0]
 [1 1 0]]

Game #16 with zero determinant:
[[1 0 1]
 [0 0 1]
 [1 0 0]]

Game #17 with zero determinant:
[[0 0 1]
 [0 0 1]
 [1 1 0]]

Game #18 with zero determinant:
[[0 0 1]
 [1 1 1]
 [0 0 0]]

Game #19 with zero determinant:
[

My friend makes random choices and I exploit the rule of sarrus

In [56]:

def calculate_determinant(matrix):
    return np.linalg.det(matrix)

#Finds a move that blocks the opponent from creating a column of '1's
def find_blocking_move(grid, n):
    for col in range(n):
        if np.sum(grid[:, col] == 1) == n - 1 and np.any(grid[:, col] == -1):
            row = np.where(grid[:, col] == -1)[0][0]
            return (row, col)
    return None

def find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns):
    """Find cells that are not in the disrupted rows and columns for strategic placement."""
    non_disrupted_cells = []
    for row in range(grid.shape[0]):
        for col in range(grid.shape[1]):
            if row not in disrupted_rows and col not in disrupted_columns and grid[row, col] == -1:
                non_disrupted_cells.append((row, col))
    return non_disrupted_cells

#Simulate a game with a dynamic strategy, with the friend making random choices
def simulate_game(n):
    grid = np.full((n, n), -1)  # Initialize grid
    
    disrupted_rows = set()
    disrupted_columns = set()

    for turn in range(n*n):
        if turn % 2 == 0:  # Friend's turn, making random choices
            empty_cells = np.argwhere(grid == -1)
            if empty_cells.size > 0:
                choice = random.choice(empty_cells)
                grid[choice[0], choice[1]] = 1
        else:  # My turn
            blocking_move = find_blocking_move(grid, n)
            if blocking_move:
                grid[blocking_move] = 0
            else:
                non_disrupted_cells = find_non_disrupted_cells(grid, disrupted_rows, disrupted_columns)
                if non_disrupted_cells:
                    choice = random.choice(non_disrupted_cells)
                    grid[choice[0], choice[1]] = 0
                else:
                    empty_cells = np.argwhere(grid == -1)
                    if empty_cells.size > 0:
                        choice = random.choice(empty_cells)
                        grid[choice[0], choice[1]] = 0

    return grid

n = 3  # Dimension of matrix
num_games = 50  # Number of games to simulate
zero_determinant_games = 0

for game in range(num_games):
    game_result = simulate_game(n)
    det = calculate_determinant(game_result)
    if det == 0:
        zero_determinant_games += 1
    print(f"Game #{game + 1} with zero determinant:\n{game_result}\nDeterminant: {det}\n")

print(f"Total games with zero determinant: {zero_determinant_games} out of {num_games}")


Game #1 with zero determinant:
[[1 1 0]
 [1 1 1]
 [0 0 0]]
Determinant: 0.0

Game #2 with zero determinant:
[[1 0 0]
 [1 1 1]
 [0 1 0]]
Determinant: -1.0

Game #3 with zero determinant:
[[0 0 1]
 [0 1 0]
 [1 1 1]]
Determinant: -1.0

Game #4 with zero determinant:
[[1 1 1]
 [0 0 1]
 [0 1 0]]
Determinant: -1.0

Game #5 with zero determinant:
[[1 1 1]
 [1 0 0]
 [0 1 0]]
Determinant: 1.0

Game #6 with zero determinant:
[[0 1 1]
 [0 0 1]
 [1 1 0]]
Determinant: 1.0

Game #7 with zero determinant:
[[1 0 0]
 [0 0 1]
 [1 1 1]]
Determinant: -1.0

Game #8 with zero determinant:
[[1 1 0]
 [1 0 0]
 [0 1 1]]
Determinant: -1.0

Game #9 with zero determinant:
[[0 1 0]
 [1 1 0]
 [1 0 1]]
Determinant: -1.0

Game #10 with zero determinant:
[[0 1 0]
 [0 1 1]
 [1 0 1]]
Determinant: 1.0

Game #11 with zero determinant:
[[0 1 1]
 [0 1 1]
 [1 0 0]]
Determinant: 0.0

Game #12 with zero determinant:
[[1 0 0]
 [1 0 1]
 [0 1 1]]
Determinant: -1.0

Game #13 with zero determinant:
[[1 1 1]
 [1 1 0]
 [0 0 0]]
Determ